# vi: set tabstop=2 :
# vi: set shiftwidth=2 :

---
driver:
  name: docker

provisioner:
  name: chef_solo
  environments_path: ./envs
  nodes_path: ./nodes
  roles_path: ./roles
  solo_rb:
    environment: DEV
    node_name: testhost
    local_mode: true
    client_key: 
    file_atomic_update: false
platforms:
  - name: centos6
    driver_config:
      use_sudo: false
      image: jrwesolo/centos-with-chef:6
      platform: rhel
suites:
  - name: default
    run_list:
      - recipe[sbg_global_search::test]
    attributes:
